apiVersion: apps/v1
kind: Deployment
metadata:
  name: productapp-api
  labels:
    app: productapp-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: productapp-api
  template:
    metadata:
      labels:
        app: productapp-api
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20