apiVersion: apps/v1
kind: Deployment
metadata:
  name: productapp-ui
  labels:
    app: productapp-ui
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: productapp-ui
  template:
    metadata:
      labels:
        app: productapp-ui
    spec:
      containers:
        - name: ui
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_API_BASE
              value: "{{ .Values.env.API_BASE }}"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10